#!/root/.venvs/mau/bin/python
"""Mutation proof for batch 30: the message list (.cm-msglist).

Each mutant breaks ONE behaviour that a msglist check in tests/run.mjs
asserts, and that assertion must go RED. A mutant that leaves the suite
green is a survivor, and a survivor is only closed when a TEST can state
the claim it broke - so every mutant carries the assertion it is aimed at
and a survivor prints its claim instead of a shrug.

The behaviours under mutation:

  * the toolbar is invisible at rest AND its column is reserved -
    opacity/pointer-events, never display:none (that drops the button out
    of the tab order, which is the keyboard's only door) and never
    position:absolute (that takes the cell out of the grid, which is the
    layout shift in slow motion), revealed by :hover AND :focus-within,
    ONE button per readable row in a fourth track that already exists;
  * one stamp per row - both stamps exist in the markup and CSS decides
    which paints, so an ungrouped row that loses its meta line, a
    continuation row that loses its gutter (its only stamp), a
    continuation row that grows a second meta line, and the quiet gutter
    becoming display:none are all failures;
  * a grouped continuation row keeps an EMPTY avatar slot in the fixed
    avatar track, the slot composes nothing, and the track's token is
    pinned to .cm-avatar's own default so a bare slot and a real avatar
    open the same width;
  * a mention is a mark AND a tint, the mark is logical and pays its
    padding back, and the row keeps the modifier the rules are written
    for;
  * a reaction count is real text, never generated by content:, and the
    reader's own chip is an edge plus aria-pressed, not a hue;
  * the frame holds: the rows stay scroller items, the system row
    composes .cm-marker instead of a second system-note style, and the
    day and unread dividers carry labels in WORDS.

Three things about the SHAPE of a mutant here, each from a real false
start rather than from principle:

  * A row-scoped mutant names the row it edits (`data-message-id="ml8"`).
    The specimen's rows are byte-identical apart from their content: the
    toolbar's own markup occurs once per row, so a bare count-1
    pre-check cannot express it, and a count-8 replacement would mutate
    every row but the one the claim is about. `--scan` requires the
    marker be unique and the fragment to occur exactly once BETWEEN it
    and the next row.
  * A mutant whose assertion is satisfied by ANY occurrence needs
    `count='all'`, not one replacement. "The timeline composes
    .cm-avatar" is `composed.length > 0`, so renaming one of the four
    avatars leaves three matches and the suite green - a survivor that
    reads like a kill. Same for "a reaction that is not the reader's
    announces itself", where two chips each satisfy the regex.
  * A mention mutant rewrites the whole `.cm-msglist__msg--mention` body
    rather than a fragment inside it: `border-inline-start: 2px` also
    matches the doc comment above the rule, so a fragment pattern would
    have to be mutated in the prose to satisfy a count-1 pre-check. Same
    for the toolbar's rest rule, whose bare tail (`opacity: 0;
    pointer-events: none;`) also matches `.cm-chart__marker`.

House rules, same as the sibling mutants in this directory: byte-exact
patterns pre-checked (--scan prints every miss with its count instead of
dying on the first), baselines before any mutation, restores in finally
and verified after. `npm test` reads dist/index.html and does NOT rebuild
- a probe left the suite green while dist still held un-mutated markup -
so every window rebuilds from the mutated source and the tree is rebuilt
once more after the final restore. A crash, a timeout or a broken build
is a KILL: surviving on a dead oracle is not passing.

--only SUBSTRING runs one mutant by label, for isolating a new pattern.
"""
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TAB = '\t'
CSS = 'src/styles/components.css'
ASTRO = 'src/pages/index.astro'
TOKENS = 'src/styles/tokens.css'

ADD_REACTION = ('<button type="button" class="cm-icon-btn" '
                'aria-label="Add a reaction to this message">+</button>')
BAR = '<div class="cm-msglist__actions">\n' + TAB * 10 + ADD_REACTION + '\n' + TAB * 9 + '</div>'

MENTION_OLD = ('.cm-msglist__msg--mention {\n' + TAB + 'border-inline-start: 2px solid var(--ink);\n'
               + TAB + 'padding-inline-start: calc(var(--space-2) - 2px);\n'
               + TAB + 'background: var(--panel-nested);\n}')


def mention(label, new_body, claim):
    """A mention mutant: the whole `.cm-msglist__msg--mention` body is
    rewritten, so the mutation cannot land in the doc comment above the
    rule - `border-inline-start: 2px` also matches the prose."""
    return [label, CSS, MENTION_OLD, new_body, claim, None, 'one']


ACTIONS_REST = ('.cm-msglist__actions {\n' + TAB + 'grid-column: 4;\n'
                + TAB + 'align-self: start;\n' + TAB + 'opacity: 0;\n'
                + TAB + 'pointer-events: none;\n}')


# [label, path, old, new, the assertion this must turn RED, row marker, count]
MUTANTS = [
    # --- A: the toolbar, hidden at rest in a column that already exists ---
    ['the toolbar ships visible at rest', CSS, ACTIONS_REST,
     ACTIONS_REST.replace('opacity: 0;', 'opacity: 1;'),
     'the toolbar must ship invisible, not merely unhovered', None, 'one'],
    ['the invisible toolbar still takes the pointer', CSS, ACTIONS_REST,
     ACTIONS_REST.replace('pointer-events: none;', 'pointer-events: auto;'),
     'the invisible toolbar still takes the pointer - it would swallow a click on the row', None, 'one'],
    ['display:none drops the button out of the tab order', CSS, ACTIONS_REST,
     ACTIONS_REST.replace(TAB + 'opacity: 0;', TAB + 'display: none;'),
     'display:none would take the button out of the tab order, so :focus-within could never open it', None, 'one'],
    ['absolute positioning gives the reserved column up', CSS,
     '\n.cm-msglist__actions {\n' + TAB + 'grid-column: 4;\n',
     '\n.cm-msglist__actions {\n' + TAB + 'position: absolute;\n' + TAB + 'grid-column: 4;\n',
     'absolute positioning takes the toolbar out of the grid, so its column is not reserved', None, 'one'],
    ['the reveal stops putting the toolbar back', CSS,
     '.cm-msglist__msg:hover .cm-msglist__actions,\n'
     '.cm-msglist__msg:focus-within .cm-msglist__actions {\n'
     + TAB + 'opacity: 1;\n' + TAB + 'pointer-events: auto;\n}',
     '.cm-msglist__msg:hover .cm-msglist__actions,\n'
     '.cm-msglist__msg:focus-within .cm-msglist__actions {\n'
     + TAB + 'opacity: 0.5;\n' + TAB + 'pointer-events: auto;\n}',
     'the reveal does not put the toolbar back', None, 'one'],
    ['the reveal stops answering the keyboard', CSS,
     '.cm-msglist__msg:hover .cm-msglist__actions,\n'
     '.cm-msglist__msg:focus-within .cm-msglist__actions {\n',
     '.cm-msglist__msg:hover .cm-msglist__actions {\n',
     'no :hover / :focus-within reveal for the toolbar', None, 'one'],
    ['the reserved action track disappears', CSS,
     'grid-template-columns: var(--msglist-gutter) var(--msglist-avatar) minmax(0, 1fr) auto;\n',
     'grid-template-columns: var(--msglist-gutter) var(--msglist-avatar) minmax(0, 1fr);\n',
     'the row grid has 3 tracks, not the 4 (gutter/avatar/message/actions) the contract reserves',
     None, 'one'],
    ['the toolbar stops being parked on its own track', CSS,
     '\n.cm-msglist__actions {\n' + TAB + 'grid-column: 4;\n',
     '\n.cm-msglist__actions {\n' + TAB + 'grid-column: auto;\n',
     'the toolbar is not parked on the fourth track, so it would land wherever auto-flow put it',
     None, 'one'],
    ['the last row ships an empty toolbar', ASTRO, BAR,
     '<div class="cm-msglist__actions"></div>',
     'the action toolbar carries 0 buttons - the contract wants ONE', 'data-message-id="ml8"', 'one'],
    ['the last row gives up its action cell', ASTRO,
     TAB * 9 + '<div class="cm-msglist__actions">\n' + TAB * 10 + ADD_REACTION + '\n' + TAB * 9 + '</div>\n',
     '',
     '6 action toolbars for 6 message rows - every row but the system note carries one',
     'data-message-id="ml8"', 'one'],

    # --- B: one stamp per row, and the gutter is a stamp too ---
    ['the gutter stops going quiet under a meta stamp', CSS,
     '.cm-msglist__msg:not(.cm-msglist__msg--grouped) .cm-msglist__gutter {\n',
     '.cm-msglist__msg:not(.cm-msglist__msg--grouped) .cm-msglist__gutter:never {\n',
     'no rule quiets the gutter on a row that already carries a meta stamp', None, 'one'],
    ['the quiet gutter is display:none instead of visibility', CSS,
     TAB + 'visibility: hidden;\n}\n',
     TAB + 'display: none;\n}\n',
     'the gutter stamp must be visibility:hidden (not removed): it is still the column the grid reserves',
     None, 'one'],
    ['a continuation row stamps itself a second time', ASTRO,
     TAB * 9 + '<div class="cm-msglist__main">\n' + TAB * 10
     + '<div class="cm-msglist__msg">\n' + TAB * 11
     + '<p class="cm-msglist__text">same author, three minutes on:',
     TAB * 9 + '<div class="cm-msglist__main">\n' + TAB * 10
     + '<p class="cm-msglist__meta"><b class="cm-msglist__author">alex</b>'
     + '<time datetime="2026-10-10T11:13">11:13</time></p>\n' + TAB * 10
     + '<div class="cm-msglist__msg">\n' + TAB * 11
     + '<p class="cm-msglist__text">same author, three minutes on:',
     'a grouped row still stamps itself in a meta line - that is the double stamp this rule exists to stop',
     None, 'one'],
    ['a continuation row loses the stamp that is its only one', ASTRO,
     TAB * 9 + '<span class="cm-msglist__gutter"><time datetime="2026-10-10T11:14">11:14</time></span>\n',
     '',
     'a grouped row has no stamp at all: the header is gone and the gutter is its only one', None, 'one'],
    ['an ungrouped row loses the meta line that stamps it', ASTRO,
     TAB * 10 + '<p class="cm-msglist__meta"><b class="cm-msglist__author">alex</b>'
     + '<time datetime="2026-10-10T11:12">11:12</time></p>\n',
     '',
     'an ungrouped row must carry exactly one meta line, with its own stamp', None, 'one'],

    # --- C: the grouped row keeps an EMPTY avatar slot ---
    ['the continuation row drops its empty avatar slot', ASTRO,
     TAB * 9 + '<span class="cm-msglist__gutter"><time datetime="2026-10-10T11:13">11:13</time></span>\n'
     + TAB * 9 + '<span class="cm-msglist__avatar"></span>\n',
     TAB * 9 + '<span class="cm-msglist__gutter"><time datetime="2026-10-10T11:13">11:13</time></span>\n',
     'N empty avatar slots for M grouped rows - the slot is what keeps the text aligned', None, 'one'],
    ['the empty slot is dressed as a real avatar', ASTRO,
     TAB * 9 + '<span class="cm-msglist__gutter"><time datetime="2026-10-10T11:14">11:14</time></span>\n'
     + TAB * 9 + '<span class="cm-msglist__avatar"></span>\n',
     TAB * 9 + '<span class="cm-msglist__gutter"><time datetime="2026-10-10T11:14">11:14</time></span>\n'
     + TAB * 9 + '<span class="cm-avatar cm-msglist__avatar" aria-hidden="true"></span>\n',
     'N empty avatar slots for M grouped rows - the slot is what keeps the text aligned', None, 'one'],
    ['the empty slot opens a different width than a real avatar', TOKENS,
     TAB + '--msglist-avatar: 2.5rem;\n',
     TAB + '--msglist-avatar: 3rem;\n',
     '--msglist-avatar is 3rem but .cm-avatar defaults to 2.5rem - an empty slot and a real avatar would open different widths',
     None, 'one'],
    ['the timeline stops composing .cm-avatar at all', ASTRO,
     'class="cm-avatar cm-msglist__avatar"',
     'class="cm-msglist__avatar"',
     'the timeline invents its own avatar instead of composing .cm-avatar', None, 'all'],

    # --- D: a mention is a mark and a tint, never a hue alone ---
    mention('the mention mark loses its width (the hue is left alone)',
            '.cm-msglist__msg--mention {\n' + TAB + 'border-inline-start: 0 solid var(--ink);\n'
            + TAB + 'padding-inline-start: calc(var(--space-2) - 2px);\n'
            + TAB + 'background: var(--panel-nested);\n}',
            'the mention bar is 0 solid - a hue with no mark, which is what the row must never be'),
    mention('the mention mark goes physical (RTL-blind)',
            '.cm-msglist__msg--mention {\n' + TAB + 'border-left: 2px solid var(--ink);\n'
            + TAB + 'padding-inline-start: calc(var(--space-2) - 2px);\n'
            + TAB + 'background: var(--panel-nested);\n}',
            'the mention mark must be logical: border-left is the wrong edge under RTL'),
    mention('the mention loses its tint (the bar is left alone)',
            '.cm-msglist__msg--mention {\n' + TAB + 'border-inline-start: 2px solid var(--ink);\n'
            + TAB + 'padding-inline-start: calc(var(--space-2) - 2px);\n'
            + TAB + 'background: transparent;\n}',
            'the mention also needs a surface step so the row reads as raised before it is read'),
    mention('the mention border stops paying its padding back',
            '.cm-msglist__msg--mention {\n' + TAB + 'border-inline-start: 2px solid var(--ink);\n'
            + TAB + 'padding-inline-start: var(--space-2);\n'
            + TAB + 'background: var(--panel-nested);\n}',
            'the mention border would shift the message column 2px against every other row'),
    ['the hover band repaints a mention as a plain row', CSS,
     '.cm-msglist__msg--mention:hover,\n.cm-msglist__msg--mention:focus-within {\n'
     + TAB + 'background: var(--panel-nested);\n}',
     '.cm-msglist__msg--mention:hover,\n.cm-msglist__msg--mention:focus-within {\n'
     + TAB + 'background: var(--bg-3);\n}',
     'the row hover band repaints a mentioned row as a plain one', None, 'one'],
    ['the mention row drops the modifier its rules are written for', ASTRO,
     'cm-msglist__msg cm-msglist__msg--mention',
     'cm-msglist__msg',
     'no mention row in the specimen - the modifier is what the rules are written for',
     None, 'one'],

    # --- E: the count is real text, and every reaction announces itself ---
    ['the count is generated by CSS instead of rendered', CSS,
     '.cm-msglist__count {\n' + TAB + 'font-weight: 700;\n',
     '.cm-msglist__count {\n' + TAB + 'content: attr(data-count);\n' + TAB + 'font-weight: 700;\n',
     'the reaction count is generated by CSS instead of rendered as text', None, 'one'],
    ['a count stops being a number a reader can select', ASTRO,
     '<span class="cm-msglist__count">2</span>',
     '<span class="cm-msglist__count">two</span>',
     'the count "two" is not a number a reader can select and copy', None, 'one'],
    ['a reaction renders without its count', ASTRO,
     'aria-pressed="false">👍 <span class="cm-msglist__count">2</span>',
     'aria-pressed="false">👍',
     'a reaction button renders without a numeric count beside its glyph', None, 'one'],
    ["the reader's own reaction loses its heavier edge", CSS,
     '.cm-msglist__reaction--mine {\n' + TAB + 'border-color: var(--ink);\n',
     '.cm-msglist__reaction--mine {\n' + TAB + 'border-color: var(--line);\n',
     "the reader's own reaction is marked by a hue alone - it needs a heavier edge", None, 'one'],
    ['mine stops announcing aria-pressed', ASTRO,
     'class="cm-msglist__reaction cm-msglist__reaction--mine" aria-pressed="true"',
     'class="cm-msglist__reaction cm-msglist__reaction--mine"',
     'the --mine reaction does not announce aria-pressed="true"', None, 'one'],
    ["no other reaction announces it is not the reader's", ASTRO,
     'class="cm-msglist__reaction" aria-pressed="false"',
     'class="cm-msglist__reaction"',
     'a reaction that is not the reader\'s must still carry aria-pressed="false"', None, 'all'],

    # --- F: the frame, the system note and the labelled dividers ---
    ['the rows stop being scroller items', ASTRO,
     '<div class="cm-scroller__item cm-msglist__msg" data-message-id="ml4" data-scroll-anchor>',
     '<div class="cm-msglist__msg" data-message-id="ml4" data-scroll-anchor>',
     'a row outside cm-scroller__item skips the scroller content-visibility contract', None, 'one'],
    ['the system row stops composing .cm-marker', ASTRO,
     'cm-msglist__msg--system" data-message-id="ml6" data-scroll-anchor>\n' + TAB * 9
     + '<div class="cm-marker cm-marker--border">',
     'cm-msglist__msg--system" data-message-id="ml6" data-scroll-anchor>\n' + TAB * 9
     + '<div class="cm-msglist__system-note">',
     'the system row does not compose .cm-marker - it would be a second system-note implementation',
     None, 'one'],
    ['the day divider loses its label', ASTRO,
     '<p class="cm-msglist__day" role="separator"><span>Today</span></p>',
     '<p class="cm-msglist__day" role="separator"></p>',
     "the day divider is not the contract's <p role=separator> with a real label", None, 'one'],
    ['the unread divider keeps the rule and loses the words', ASTRO,
     '<div class="cm-msglist__unread" role="separator"><span>2 unread messages</span></div>',
     '<div class="cm-msglist__unread" role="separator"><span>2</span></div>',
     'the unread divider must carry its label as words, not as a rule alone', None, 'one'],
    ['the nav index drops the section', ASTRO,
     "'scroller', 'msglist', 'attachment',",
     "'scroller', 'attachment',",
     'the nav index has no msglist entry, so the scroll-spy skips it', None, 'one'],
]

SUITE_CMD = 'npm test'


def run_check(cmd, timeout=300):
    try:
        r = subprocess.run(cmd, shell=True, cwd=ROOT, capture_output=True,
                           text=True, timeout=timeout)
        return r.returncode, (r.stdout or '') + (r.stderr or '')
    except subprocess.TimeoutExpired:
        return -1, 'TIMEOUT (treated as a kill: an oracle that cannot run is not an oracle that passed)'


def build():
    """`npm test` reads dist/index.html and never rebuilds it, so every
    window rebuilds from the mutated source - otherwise a src/ mutant is
    graded against the markup that was built before it."""
    try:
        r = subprocess.run(['npm', 'run', 'build'], cwd=ROOT, capture_output=True,
                           text=True, timeout=300)
        return r.returncode == 0
    except subprocess.TimeoutExpired:
        return False


def row_span(text, marker):
    """From the marker to the next row: the window a row-scoped mutant is
    allowed to touch."""
    i = text.index(marker)
    nxt = text.find('data-message-id="', i + len(marker))
    return i, (nxt if nxt != -1 else len(text))


def scoped(text, old, marker):
    """(a, b, haystack) for the replacement(s) inside the row `marker`."""
    if marker is None:
        return 0, len(text), text
    i, j = row_span(text, marker)
    return i, j, text[i:j]


def preflight(src, old, new, marker, count):
    """Why this mutant is malformed against its source, or None. A
    `count='all'` mutant asserts a claim satisfied by ANY occurrence, so
    it needs 2+ matches to actually change anything."""
    if old == new:
        return 'old and new are identical'
    if marker is not None and src.count(marker) != 1:
        return f'row marker {marker} matches {src.count(marker)}'
    _a, _b, hay = scoped(src, old, marker)
    n = hay.count(old)
    where = 'inside the row' if marker else 'in the file'
    if count == 'all':
        return None if n >= 2 else f'pattern matches {n} {where}; a count-all sweep needs 2+'
    return None if n == 1 else f'pattern matches {n} {where}, not 1'


if '--scan' in sys.argv:
    bad = 0
    for name, path, old, new, _claim, marker, count in MUTANTS:
        why = preflight((ROOT / path).read_text(), old, new, marker, count)
        if why:
            print(f'  PATTERN ABSENT - {name} [{path}]: {why}')
            bad += 1
    print(f'{len(MUTANTS) - bad}/{len(MUTANTS)} patterns present')
    sys.exit(2 if bad else 0)

only = sys.argv[sys.argv.index('--only') + 1] if '--only' in sys.argv else None
chosen = [m for m in MUTANTS if only is None or only in m[0]]
if only is not None:
    print(f'--only {only!r}: {len(chosen)}/{len(MUTANTS)} mutants')

originals = {p: (ROOT / p).read_text() for p in {m[1] for m in chosen}}

for name, path, old, new, _claim, marker, count in chosen:
    why = preflight(originals[path], old, new, marker, count)
    assert not why, f'PATTERN ABSENT: {name} ({why})'

assert build(), 'baseline build broke'
rc, out = run_check(SUITE_CMD)
assert rc == 0, f'baseline suite not green:\n{out[-2000:]}'
last = [l.strip() for l in out.strip().splitlines() if l.strip()][-1]
print(f'baseline: {last}', end=' | ', flush=True)
assert build(), 'baseline rebuild broke'
print('build green', flush=True)

killed, survived = [], []
for name, path, old, new, claim, marker, count in chosen:
    src = originals[path]
    a, b, _hay = scoped(src, old, marker)
    mutated = src[:a] + src[a:b].replace(old, new, -1 if count == 'all' else 1) + src[b:]
    assert mutated != src, f'MUTATION DID NOT LAND: {name}'
    if count == 'all':
        assert old not in mutated[a:b], f'MUTATION INCOMPLETE (scope): {name}'
    elif marker is None:
        assert src.count(old) == 1, f'MUTATION NOT SCOPED: {name}'
    (ROOT / path).write_text(mutated)
    try:
        if not build():
            rc, out = -1, 'build broke under the mutation'
        else:
            rc, out = run_check(SUITE_CMD)
        dead = (rc != 0) or ('FAIL' in out) or ('not ok' in out)
        how = ('BUILD BROKE' if 'build broke' in out and rc == -1 else
               ('TIMEOUT' if rc == -1 else ('FAIL-line' if dead else f'rc={rc}')))
        (killed if dead else survived).append((name, claim, how))
        print(f'  {"killed" if dead else "SURVIVED"} - {name} :: {how}', flush=True)
    finally:
        (ROOT / path).write_text(originals[path])

for p, data in originals.items():
    assert (ROOT / p).read_text() == data, f'RESTORE FAILED: {p} - crash, not a result'
assert build(), 'post-run rebuild failed - the tree is restored but dist is stale'

if survived:
    print('\nSURVIVED (no assertion states this claim):')
    for name, claim, how in survived:
        print(f'  - {name} :: {how}\n      the assertion that should have failed: {claim}')
print(f'killed={len(killed)} survived={len(survived)} of {len(chosen)}')
sys.exit(0 if not survived else 1)
